### ISSUE TITLE
missing credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/pendulum-lab#43] opened 2015-01-30 18:51 UTC
See pendulum-lab-main.js.  simOptions.credits needs to be populated.

**Comment by pixelzoom** [comment] 2015-01-30 18:59
Assigning to @jonathanolson to instruct MLL on what the credits should be.

**Comment by jonathanolson** [comment] 2015-01-31 02:58
Duplicate of https://github.com/phetsims/pendulum-lab/issues/27, closing.

**Closed by jonathanolson** 2015-01-31 02:58 UTC
Labels: code review
