### ISSUE TITLE
Thermal Energy Reset Button

### ISSUE THREAD

**Issue by memo330179** [phetsims/pendulum-lab#149] opened 2016-06-28 12:39 UTC
On the pendulum lab energy tab, there is a dynamically updating graph of the mechanical and thermal energy. After a while, the thermal energy "takes over" the graph and there is no way to reset it without resetting the pendulum along with it. There is a similar graph in energy skate park which uses a reset button that only resets the thermal energy. Is this something which would be useful to the user in the Pendulum lab?

![screenshot from 2016-06-28 08-34-54](https://cloud.githubusercontent.com/assets/11654721/16415453/445184ce-3d0b-11e6-9d4c-88e814022995.png) 

![screenshot from 2016-06-28 08-35-53](https://cloud.githubusercontent.com/assets/11654721/16415530/b208aa42-3d0b-11e6-9408-6f0e95e77e23.png)

**Comment by arouinfar** [comment] 2016-06-30 17:34
This is a great suggestion @memo330179!

The use case of the reset thermal energy button in ESPB is a little different from Pendulum Lab. Primarily, the button was designed to remove the heat energy accidentally introduced through a collision between the skater and the track (caused by dropping the skater onto the track). However, it can also used to remove the accumulated thermal energy from the system while the skater is in motion (though this may be a less common use).

That being said, I can see a remove thermal energy button being a useful addition to PL. Thermal energy can quickly accumulate and it becomes hard to resolve the remaining energy in the system. I'll mock it up and see how it looks.

**Comment by veillette** [comment] 2016-08-10 16:05
pinging @arouinfar : tell me what you think about the thermal reset button. It is functional. 
Should we keep it?, if we keep it is the location appropriate?, size?

let me know if you can't see from master and I'll deploy a dev version.

**Comment by arouinfar** [comment] 2016-08-10 16:56
@veillette I took a look at master, and in general, this addition looks good. However, I'm a little concerned by how much vertical space we lose in the graph, particularly on the Lab screen.

Let's reduce the size of the remove heat button by 15%, but keep the same bottom alignment. The horizontal axis can then be shifted down a little to fill in the empty space. To compensate for the smaller button size, let's keep the touch area the same size. Here's a mockup showing the updated size (axis shift not mocked up). 

![image](https://cloud.githubusercontent.com/assets/8419308/17562485/59ed71fe-5ee8-11e6-83f2-220e8688b380.png)

Assigning to @veillette.

**Comment by veillette** [comment] 2016-08-11 22:58
![image](https://cloud.githubusercontent.com/assets/7633344/17607552/7627c27c-5ff4-11e6-8155-4e09f5fe5738.png)

With pointerAreas

![image](https://cloud.githubusercontent.com/assets/7633344/17607578/9d97a94e-5ff4-11e6-8310-57eeeb46cfeb.png)

I move down the graph a bit. 
I lower the cornerRadius value of the button so that it doesn't look too round.

**Comment by veillette** [comment] 2016-08-11 22:59
The commit is on master. Assigning to @arouinfar for input. 

We can a live-skype session if you want to tweak it differently.

**Comment by arouinfar** [comment] 2016-08-11 23:01
Looks good @veillette! The click (blue) and touch (red) areas on the remove thermal energy button look reversed, though.

**Comment by veillette** [comment] 2016-08-11 23:07
Good catch,
![image](https://cloud.githubusercontent.com/assets/7633344/17607881/c50477c6-5ff6-11e6-854f-ae3795ec399c.png)

**Comment by veillette** [comment] 2016-08-11 23:23
That should fix it. If you are happy with the result. feel free to close.

**Comment by arouinfar** [comment] 2016-08-11 23:52
:+1:

**Closed by arouinfar** 2016-08-11 23:52 UTC
Labels: design:general
