### ISSUE TITLE
Period timer measures more time in slow motion

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/pendulum-lab#93] opened 2015-06-10 17:30 UTC
Test device: iPad2

Operating System: iOS 8.3

Browser: Safari

Problem description: The Period timer measures more time passing when slow motion is on. With the stopwatch the seconds actually tick slower in slow motion, which is how I think it's supposed to be also for the period timer.

Steps to reproduce: Start period timer when pendulum is in motion. Switch to slow motion. Start period timer again. Compare.

Severity: 

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/8089263/fdef374a-0f63-11e5-8ac6-9a040843f37a.png)

![image](https://cloud.githubusercontent.com/assets/12610678/8089271/07c4d4f0-0f64-11e5-8cf7-2d9c340da01b.png)
Troubleshooting information (do not edit):
Name: Pendulum Lab
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.4/pendulum-lab_en.html
Version: 1.0.0-dev.4 2015-06-04 17:46:07 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x768

Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# pendulum-lab 1.0.0-dev.4 Thu Jun 04 2015 11:46:00 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"7de4a27be4b322b71c5f5046df193a03ccf0f161","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"c7d6ea5f9bef6e3882309af56ad409908dd28878","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"pendulum-lab":{"sha":"2b4cf70e4a8a88b37882b1643d44155a806508ab","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"c9087fbb0cdd83f79452330fec3b83f809e2c0d8","branch":"master"}}

**Comment by arouinfar** [comment] 2015-06-12 20:28
I think this issue is mostly likely related to #94. In OSX 10.9.5/Chrome 43, I recorded the period the default length and mass at 28* several times in Normal and Slow Motion. 

Normal: 2.5180 s, 2.5330 s, 2.5350 s, 2.5340 s
Slow Motion: 2.5292 s, 2.5395 s, 2.5274 s, 2.5282 s

**Comment by andrey-zelenkov** [comment] 2015-06-28 14:59
This issue is duplicate #94 and imho can be closed. They have exactly the same problem and when one of them will be fixed, then another one will be fixed too.

**Comment by arouinfar** [comment] 2015-07-08 17:21
I agree, this looks like a duplicate of #94. Closing.

**Closed by arouinfar** 2015-07-08 17:21 UTC
Labels: bug
