### ISSUE TITLE
Dev boundary has inconsistent width

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#167] opened 2017-07-14 18:12 UTC
Using ?dev, the width on the home screen does not match the width within the sim.
![image](https://user-images.githubusercontent.com/8419308/28224717-6ca98d8c-688d-11e7-89b9-9984853ca8e0.png)
![image](https://user-images.githubusercontent.com/8419308/28224731-7730f402-688d-11e7-9f0e-d036f6fef30a.png)

@jonathanolson not sure how much of an issue this is, but the inconsistency makes it a bit harder to recommend layout changes for #165.

**Comment by jonathanolson** [comment] 2017-07-14 22:13
This is caused by the sim having specified an atypical (I believe older) layout bounds (with a different aspect ratio).

The home screen has the normal (default) one. See https://github.com/phetsims/pendulum-lab/issues/165#issuecomment-315466865 for details

**Comment by jonathanolson** [comment] 2017-07-14 22:13
Requested permission for me to switch to the normal layout bounds (normal aspect ratio) in that issue, assigning for that question here.

**Comment by jonathanolson** [comment] 2017-07-14 23:32
Committed initial changes for this.

Note that the "dev" bounds for the home screen do still include the navbar for the home screen, while they don't include the navbar for sim screens. This is expected, and now the aspect ratios match (left/right layout bounds locations won't change).

**Closed by jonathanolson** 2017-07-14 23:32 UTC
